"""add fields to chat_logs

Revision ID: 1c48b71d0b57
Revises: 81d154803ea8
Create Date: 2025-07-11 11:49:11.370375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c48b71d0b57'
down_revision: Union[str, None] = '81d154803ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('code', sa.Integer(), nullable=True))
    op.add_column('chat_logs', sa.Column('ttft_ms', sa.Float(), nullable=True))
    op.add_column('chat_logs', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_logs', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_logs', sa.Column('audio_seconds', sa.String(), nullable=True))
    op.add_column('chat_logs', sa.Column('request_id', sa.String(), nullable=True))
    op.add_column('chat_logs', sa.Column('error', sa.Text(), nullable=True))
    op.alter_column('chat_logs', 'latency_ms',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_chat_logs_api_key', table_name='chat_logs')
    op.drop_column('chat_logs', 'request_text')
    op.drop_column('chat_logs', 'response_text')
    op.drop_column('chat_logs', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('chat_logs', sa.Column('response_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('chat_logs', sa.Column('request_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index('ix_chat_logs_api_key', 'chat_logs', ['api_key'], unique=False)
    op.alter_column('chat_logs', 'latency_ms',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('chat_logs', 'error')
    op.drop_column('chat_logs', 'request_id')
    op.drop_column('chat_logs', 'audio_seconds')
    op.drop_column('chat_logs', 'output_tokens')
    op.drop_column('chat_logs', 'input_tokens')
    op.drop_column('chat_logs', 'ttft_ms')
    op.drop_column('chat_logs', 'code')
    # ### end Alembic commands ###
