"""remove chat_id from chatlog

Revision ID: 4ede5d6262e5
Revises: 95571549653a
Create Date: 2025-07-09 14:11:23.118502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ede5d6262e5'
down_revision: Union[str, None] = '95571549653a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_logs_chat_id', table_name='chat_logs')
    op.drop_constraint('chat_logs_chat_id_fkey', 'chat_logs', type_='foreignkey')
    op.drop_column('chat_logs', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chat_logs_chat_id_fkey', 'chat_logs', 'chats', ['chat_id'], ['id'])
    op.create_index('ix_chat_logs_chat_id', 'chat_logs', ['chat_id'], unique=False)
    # ### end Alembic commands ###
