"""Add last_used_at and usage_24h to APIKey

Revision ID: 61e45e05474d
Revises: 18a238fde976
Create Date: 2025-07-07 11:14:26.859862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e45e05474d'
down_revision: Union[str, None] = '18a238fde976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.add_column('api_keys', sa.Column('usage_24h', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'usage_24h')
    op.drop_column('api_keys', 'last_used_at')
    # ### end Alembic commands ###
